name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true
            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with: 
                gradle-version: 8.8
            - name: Build with Gradle
              run: gradle build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with: 
                name: builds
                path: ./build/libs/realistic_electricity*.jar